name: CESSON 3.0 Sexy and Simple Marketing Agency
favicon: null
layout_spectrum: 0.88989
typography_spectrum: 0.808
title: CESSON 3.0 Sexy and Simple Marketing Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a12426'
    - '#bfbfbf'
    - '#808080'
  brandStrength: 0.4309412781149149
  lightness: 0.9659482988063246
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
