name: cesson
favicon: null
layout_spectrum: 0.24139
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4309412781149149
  lightness: 0.9659482988063246
  saturation: 0.05971323628909886
  rhythmicContrast: 0.7945256014354527
purpose: []
